---
#
# Google home alarm template sensor
#
- platform: template
  sensors:
    google_home_alarm_sensor:
      value_template: >
        {% set ts = as_timestamp(states("sensor.google_home_alarm")) %}
        {% if ts is not none %}
          {{ states("sensor.time") == (ts - 10*60)|timestamp_custom ("%H:%M") }}
        {% else %}
          False
        {% endif %}
