---
# These sensors keep track of how long ago (in days) I did a certain task in the household
# Maybe put -1 back?

# Vacuuming
- platform: template
  sensors:
    days_after_vacuuming:
      friendly_name: Dagen na Stofzuigen
      unit_of_measurement: 'dagen'
      value_template: "{{ states('sensor.time') and ((as_timestamp(now()) - state_attr('input_datetime.vacuuming','timestamp')) | int / 86400) | round(0) }}"

# Mopping
- platform: template
  sensors:
    days_after_mopping:
      friendly_name: Dagen na Dweilen
      unit_of_measurement: 'dagen'
      value_template: "{{ states('sensor.time') and ((as_timestamp(now()) - state_attr('input_datetime.mopping','timestamp')) | int / 86400) | round(0) }}"

# Cleaning the bathroom
- platform: template
  sensors:
    days_after_cleaning_the_bathroom:
      friendly_name: Dagen na Badkamer schoonmaken
      unit_of_measurement: 'dagen'
      value_template: "{{ states('sensor.time') and ((as_timestamp(now()) - state_attr('input_datetime.cleaning_the_bathroom','timestamp')) | int / 86400) | round(0) }}"

# Clean the toilet
- platform: template
  sensors:
    days_after_clean_the_toilet:
      friendly_name: Dagen na Toilet schoonmaken
      unit_of_measurement: 'dagen'
      value_template: "{{ states('sensor.time') and ((as_timestamp(now()) - state_attr('input_datetime.clean_the_toilet','timestamp')) | int / 86400) | round(0) }}"

# Dust off
- platform: template
  sensors:
    days_after_dust_off:
      friendly_name: Dagen na Afstoffen
      unit_of_measurement: 'dagen'
      value_template: "{{ states('sensor.time') and ((as_timestamp(now()) - state_attr('input_datetime.dust_off','timestamp')) | int / 86400) | round(0) }}"

# Beddengoed verschonen
- platform: template
  sensors:
    days_after_change_bedding:
      friendly_name: Dagen na beddengoed verschonen
      unit_of_measurement: 'dagen'
      value_template: "{{ states('sensor.time') and ((as_timestamp(now()) - state_attr('input_datetime.change_bedding','timestamp')) | int / 86400) | round(0) }}"

# Studio opruimen
- platform: template
  sensors:
    days_after_clean_up_studio:
      friendly_name: Dagen na Opruimen studio
      unit_of_measurement: 'dagen'
      value_template: "{{ states('sensor.time') and ((as_timestamp(now()) - state_attr('input_datetime.clean_up_studio','timestamp')) | int / 86400) | round(0) }}"
