---
# Calculate the difference between inside and outside temperature
#
- platform: template
  sensors:
    temperature_difference_in_out:
      friendly_name: "verschil binnen/buiten temperatuur"
      unit_of_measurement: '°C'
      value_template: >-
        {% if is_state('sensor.openweathermap_temperature', 'unknown') %}
          unkown
        {% else %}
          {{ ( states('sensor.home_temperature') | float - states('sensor.openweathermap_temperature') | float ) | round(1) }}
        {% endif %}
      device_class: temperature
