---
#
# https://github.com/Paul-dH/Home-Assisant-Sensor-OvApi#sensor-configuration-examples

########## Richting centraal station ##########
# Bus 57 / 237 richting centraal station
- platform: ovapi
  name: Bushalte_blauwe_vogelweg_1
  timing_point_code: 54442060
  show_future_departures: 4

# Bus 43 richting centraal station
- platform: ovapi
  name: Bushalte_zernikedreef_43
  timing_point_code: 42033701
  show_future_departures: 4

# Bus 221 richting centraal station
- platform: ovapi
  name: Bushalte_zernikedreef_221
  timing_point_code: 54440720
  show_future_departures: 4

########## Richting huis ##########
# Bus 57 richting Blauwe vogelweg
- platform: ovapi
  name: Bushalte_centraal_station_57
  timing_point_code: 54447800
  show_future_departures: 4

# Bus 237 richting Blauwe vogelweg
- platform: ovapi
  name: Bushalte_centraal_station_237
  timing_point_code: 54447750
  show_future_departures: 4

# Bus 37 richting Blauwe Vogelweg (alleen in het weekend)

# Bus 43 richting Darwinweg/Zernikedreef
- platform: ovapi
  name: Bushalte_centraal_station_43
  timing_point_code: 54447220
  show_future_departures: 4

# Bus 221 richting Darwinweg/Zernikedreef
- platform: ovapi
  name: Bushalte_centraal_station_221
  timing_point_code: 54447880
  show_future_departures: 4
