---
homeassistant:
  # Name of the location where Home Assistant is running
  name: Student Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret homeassistant_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization #
  customize: !include_dir_merge_named customizations/entities
  # Lets me custimize all entities in a domain
  customize_domain: !include_dir_merge_named customizations/domains
  # Packages #
  packages: !include_dir_named integrations

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Discover some devices automatically
discovery:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

python_script:
