---
# This is actually just a bootstrap for my Lovelace configuration.

# It loads all resources for Lovelace dynamically from subfolders
# inside the `lovelace/resources` directory.
#
# Views are actually include one by one, this to guarentee the order of
# the tabs of the view in the UI.
#
title: Student Home
resources: !include_dir_list lovelace/resources
cch: !include lovelace/cards/custom_compact_header.yaml
views:
  - !include lovelace/views/dashboard.yaml
  - !include lovelace/views/security.yaml
  - !include lovelace/views/temperature.yaml
  - !include lovelace/views/household.yaml
  - !include lovelace/views/media_player.yaml
  - !include lovelace/views/public_transport.yaml
  - !include lovelace/views/parcel_delivery.yaml
  - !include lovelace/views/automations.yaml
  - !include lovelace/views/system.yaml
