---
# This is actually just a bootstrap for my Lovelace configuration.

# It loads all resources for Lovelace dynamically from subfolders
# inside the `lovelace/resources` directory.
#
# Views are actually include one by one, this to guarentee the order of
# the tabs of the view in the UI.
#
title: Student Home
resources: !include_dir_list lovelace/resources
cch:
  menu: show
  notifications: clock
  voice: hide
  options: show
  clock_format: 24
  clock_am_pm: false
  clock_date: false
  exceptions:
    - conditions:
        user_agent: Mobile
      config:
        menu: overflow
        notifications: overflow
        swipe: true
        swipe_animate: swipe
views:
  - !include lovelace/views/dashboard.yaml
  - !include lovelace/views/household.yaml
  - !include lovelace/views/media_player.yaml
  - !include lovelace/views/public_transport.yaml
  - !include lovelace/views/parcel_delivery.yaml
  - !include lovelace/views/automations.yaml
  - !include lovelace/views/system.yaml
