---
- alias: '[Light] - Control all lights'
  description: >-
    Control all the lights with a blueprint
    for Aqara Opple 6-way remote

  id: a6b6292e-7409-4e39-9882-f654f291b943

  use_blueprint:
    path: opple_6way_remote_lights.yaml
    input:
      brightness: '50'
      remote: 6658bdeac29140269a715442ac5b56f0
      light_1:
        entity_id: light.hal
      light_2:
        entity_id: light.keuken
      light_3:
        entity_id: light.woonkamer
