---
# Automate the bathroom light
# The lights go on by opening the door and goes off every 15 minutes when the door is closed
# Also the lights will be dimmed in the night
#
- alias: '[Light] - Turn ON bathroom light'
  description: >-
    Turn the light on when I open a door or if there is motion

  id: 2498664e-7b8d-4de5-9613-25435b183274
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.openclose_sensor_4, binary_sensor.motion_badkamer
      to: 'on'
      from: 'off'
  action:
    - service: light.turn_on
      entity_id: light.badkamer
      data_template:
        brightness: >
          {% if is_state ('binary_sensor.night' , 'on') %} 13
          {% else %} 115
          {% endif %}

- alias: '[Light] - Turn OFF bathroom light'
  description: >-
    Turn the light off when there is no motion for 6 minutes

  id: 40f79c91-8483-4ef7-b6d5-4025ad306276
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.motion_badkamer
      to: 'off'
      for:
        minutes: 6
  condition:
    # Keep the light on when you take a shower
    - condition: numeric_state
      entity_id: sensor.bathroom_humidity
      below: 75
  action:
    - service: light.turn_off
      data:
        entity_id: light.badkamer
