---
#
# Turn the lights on in the evening if LUX value is low
#
- alias: '[Light] - Set lights on in the evening'
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.woonkamer_light_sensor
      below: 15
    - platform: numeric_state
      entity_id:
        - sensor.kitchen_light_sensor
      below: 5
  condition:
    # Check if I'm home :)
    - condition: state
      entity_id: sensor.klaas_status
      state: 'Thuis'
    # Prevent trigger in the morning/night
    - condition: time
      after: '15:00:00'
  action:
    - choose:
        # Hal and kitchen
        - conditions:
            - condition: template
              value_template: "{{ trigger.entity_id == 'sensor.kitchen_light_sensor' }}"
            # Check if light are off
            - condition: state
              entity_id: light.hal
              state: 'off'
            - condition: state
              entity_id: light.keuken
              state: 'off'
          sequence:
            - service: light.turn_on
              entity_id:
                - light.hal
                - light.keuken
              data:
                brightness: 51

        # Living room
        - conditions:
            - condition: template
              value_template: "{{ trigger.entity_id == 'sensor.woonkamer_light_sensor' }}"
            # Check if light are off
            - condition: state
              entity_id: light.woonkamer
              state: 'off'
          sequence:
            - service: light.turn_on
              entity_id: light.woonkamer
              data:
                brightness: 64

# Automate the lamps for when you return home
- alias: '[Light] - Turn on light when come home'
  trigger:
    - platform: state
      entity_id: binary_sensor.openclose_sensor_1
      to: 'on'
  condition:
    # Just arrived
    - condition: state
      entity_id: sensor.klaas_status
      state: 'Net Aangekomen'
    - condition: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      below: 3
  action:
    - service: scene.turn_on
      entity_id: scene.avond
