---
# Using the IKEA Dimmer (small round white disk) to turn on / off the kitchen lights
#
- alias: '[Light] - Toggle all lights ON'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: symfonisk_sound_controller
        event: 1002
  action:
    service: scene.turn_on
    entity_id: scene.avond

- alias: '[Light] - Toggle all lights OFF'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: symfonisk_sound_controller
        event: 1004
  action:
    service: light.turn_off
    entity_id:
      - light.keuken
      - light.hal
      - light.woonkamer

- alias: 'Increase brightness of lamp from dimmer'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: symfonisk_sound_controller
      event: 3001
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.keuken
        brightness: >
          {% set bri = state_attr('light.keuken', 'brightness') | int %}
          {{ [bri+30, 249] | min }}

- alias: 'Decrease brightness of lamp from dimmer'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: symfonisk_sound_controller
      event: 2001
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.keuken
        brightness: >
          {% set bri = state_attr('light.keuken', 'brightness') | int %}
          {{ [bri-30, 0] | max }}
