---
# https://github.com/sleevezipper/hass-workstation-service
#
- alias: '[Light] - Set lights for meeting'
  description: >-
    It will change my workdesk lights for online meetings
    based on my webcam status

  id: fee85b75-a744-4fd4-ad61-2de0a35a340d
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.laptop_webcam
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.laptop_webcam
      from: 'on'
      to: 'off'
  condition:
    # Check if I'm home :)
    - condition: state
      entity_id: sensor.klaas_status
      state: 'Thuis'
  action:
    - choose:
        # Into a meeting
        - conditions:
            - condition: state
              entity_id: binary_sensor.laptop_webcam
              state: 'on'
          sequence:
            - service: scene.create
              data:
                scene_id: workdesk_before
                snapshot_entities:
                  - light.wled_workdesk
                  - light.blitzwolf_bw_lt11_led_strip_links
                  - light.blitzwolf_bw_lt11_led_strip_rechts
            - service: scene.turn_on
              target:
                entity_id: scene.bureau_work
              data:
                transition: 1
        # Exit a meeting
        - conditions:
            - condition: state
              entity_id: binary_sensor.laptop_webcam
              state: 'off'
          sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.workdesk_before
