---
- alias: '[Light] - Set wardrobe lights'
  description: >-
    These automations ensure that the lights above my wardrobe
    will go on or off based on the door sensors.

  id: 8c0b35c6-0917-4768-aabc-b4235301c115
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.wardrobe
  action:
    - alias: "Turn lights OFF if group off else turn light ON"
      choose:
        - alias: "Doors are closed"
          conditions:
            - condition: state
              entity_id: binary_sensor.wardrobe
              state: 'off'
          sequence:
            - service: scene.turn_on
              target:
                entity_id: scene.wardrobe_before
      default:
        - service: scene.create
          data:
            scene_id: wardrobe_before
            snapshot_entities:
              - light.hal
        - service: light.turn_on
          target:
            entity_id: light.hal
          data:
            brightness: 128
