---
########## Automations ###########
id: automation
icon: mdi:creation
title: Automatisering
path: automations
cards:
  # System
  - type: custom:auto-entities
    card:
      type: entities
      title: System Automations
      show_header_toggle: false
    filter:
      include:
        - entity_id: automation.system*
          options:
            type: custom:multiple-entity-row
            toggle: true
            secondary_info: last-changed
      exclude:
        - entity_id: automation.system_ifttt_handling
        - entity_id: automation.system_perform_system_checks
        - entity_id: automation.system_perform_log_checks

  # People
  - type: custom:auto-entities
    card:
      type: entities
      title: People Automations
      show_header_toggle: false
    filter:
      include:
        - entity_id: automation.people*
          options:
            type: custom:multiple-entity-row
            toggle: true
            secondary_info: last-changed

  # House
  - type: custom:vertical-stack-in-card
    cards:
      # House
      - type: custom:auto-entities
        card:
          type: entities
          title: House Automations
          show_header_toggle: false
        filter:
          include:
            - entity_id: automation.house*
              options:
                type: custom:multiple-entity-row
                toggle: true
                secondary_info: last-changed
      - type: divider
      # Lights
      - type: custom:auto-entities
        card:
          type: entities
          title: Light
          show_header_toggle: false
        filter:
          include:
            - entity_id: automation.light*
              options:
                type: custom:multiple-entity-row
                toggle: true
                secondary_info: last-changed
      - type: divider
      # Media
      - type: custom:auto-entities
        card:
          type: entities
          title: Media
          show_header_toggle: false
        filter:
          include:
            - entity_id: automation.media*
              options:
                type: custom:multiple-entity-row
                toggle: true
                secondary_info: last-changed
