---
########## Automations ###########
id: automation
icon: mdi:creation
title: Automatisering
path: automations
cards:
  # System
  - type: custom:monster-card
    card:
      type: entities
      title: System Automations
      show_header_toggle: false
    filter:
      include:
        - entity_id: automation.system*
      exclude:
        - entity_id: automation.system_ifttt_handling
        - entity_id: automation.system_perform_system_checks
        - entity_id: automation.system_perform_log_checks

  # People
  - type: custom:monster-card
    card:
      type: entities
      title: People Automations
      show_header_toggle: false
    filter:
      include:
        - entity_id: automation.people*
      exclude:
        - entity_id: automation.people_reset_already_fired_boolean

  # House
  - type: custom:vertical-stack-in-card
    cards:
      # House
      - type: custom:monster-card
        card:
          type: entities
          title: House Automations
          show_header_toggle: false
        filter:
          include:
            - entity_id: automation.house*
      - type: divider
      # Lights
      - type: custom:monster-card
        card:
          type: entities
          title: Light
          show_header_toggle: false
        filter:
          include:
            - entity_id: automation.light*
