---
# If I forget something, Home Assistant will let me know.
#
- alias: '[People] - Forgot the lights'
  description: >-
    Automation for when a light is still ON in my house

  id: fb712601-6f02-4908-9ec1-4213ca66a99b
  mode: single

  trigger:
    # Outside home zone
    - platform: zone
      entity_id: person.klaas_schoute
      zone: zone.home
      event: leave
  condition:
    condition: or
    conditions:
      # If a light is still on
      - condition: state
        entity_id: light.woonkamer
        state: 'on'
      - condition: state
        entity_id: light.keuken
        state: 'on'
      - condition: state
        entity_id: light.hal
        state: 'on'
      - condition: state
        entity_id: light.badkamer
        state: 'on'
      - condition: state
        entity_id: light.stellingkast
        state: 'on'
  action:
    # HA Android notification
    - service: notify.mobile_app_klaas_samsung_s20_plus
      data:
        title: 'Lampen vergeten!'
        message: >
          Je bent vertrokken, maar de lampen staan nog aan.
        data:
          actions:
            - action: turn_light_off
              title: Zet lampen UIT

- alias: '[Light] - Turn all light off'
  description: >-
    Turn all light of when start action from notification

  id: ca887d6b-7d28-4150-b821-4002f996a0f5
  mode: single

  trigger:
    # Actionable notification event trigger
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: turn_light_off
  action:
    # Turn all lights off
    - service: script.turn_on
      entity_id: script.all_lights_off
