---
# Custom icons for the light automations
automation.light_control_all_lights:
  icon: mdi:lightbulb-multiple-outline
automation.light_turn_all_light_off:
  icon: mdi:lightbulb-multiple-outline
automation.light_turn_lights_off_automated:
  icon: mdi:lightbulb-multiple-outline
automation.light_turn_lights_on_automated:
  icon: mdi:lightbulb-multiple-outline
automation.light_turn_off_bathroom_light:
  icon: mdi:lightbulb-multiple-outline
automation.light_turn_on_bathroom_light:
  icon: mdi:lightbulb-multiple-outline
automation.light_turn_on_light_when_come_home:
  icon: mdi:lightbulb-multiple-outline
automation.light_turn_wardrobe_light_off:
  icon: mdi:lightbulb-multiple-outline
automation.light_turn_wardrobe_light_on:
  icon: mdi:lightbulb-multiple-outline
