---
# Custom icons for the light automations
automation.light_toggle_lamp_on_from_dimmer:
  icon: mdi:light-switch
automation.light_toggle_lamp_off_from_dimmer:
  icon: mdi:light-switch
automation.light_set_lights_on_in_the_evening:
  icon: mdi:light-switch
automation.light_turn_on_light_when_come_home:
  icon: mdi:light-switch
