---
# Custom icons for the people automations
automation.people_forgot_the_lights:
  icon: mdi:account-outline

automation.people_it_is_a_false_alarm:
  icon: mdi:account-outline

automation.people_warn_in_case_of_emergency:
  icon: mdi:account-outline