---
# Custom icons for the presence automations
automation.presence_markeer_persoon_als_lang_weg:
  icon: mdi:account-outline
automation.presence_markeer_persoon_als_net_aangekomen:
  icon: mdi:account-outline
automation.presence_markeer_persoon_als_net_vertrokken:
  icon: mdi:account-outline
automation.presence_markeer_persoon_als_thuis:
  icon: mdi:account-outline
automation.presence_markeer_persoon_als_weg:
  icon: mdi:account-outline
