---
#
#
- alias: '[Tv] - Toggle TV power'
  trigger:
    - platform: state
      entity_id: input_boolean.tv_power
  action:
    service: remote.send_command
    data_template:
      entity_id: remote.harmony_hub
      device: 64401392
      command: >
        {% if is_state(trigger.entity_id, 'on') %}
          PowerOn
        {% else %}
          PowerOff
        {% endif %}
