---
# Notify me when the SSL certificate will expire soon
#
- alias: '[System] - Notify SSL techlife.com expire'
  description: >-
    Get a notification on my phone when the SSL certificate will expire

  id: 0d8a6fef-2a76-454a-9866-2d8305726c42
  mode: single

  use_blueprint:
    path: bkbilly/certificate-expiration.yaml
    input:
      time_input: '12:00:00'
      certificate_input: sensor.cert_expiry_timestamp_techlife_com
      days_input: 30
      notify_device: 5e3a9bc1a6710fb13b08435ab16cd62b

- alias: '[System] - Notify SSL techlife.nl expire'
  description: >-
    Get a notification on my phone when the SSL certificate will expire

  id: 2cf3d5c1-3d04-45a9-83ed-769a12db710a
  mode: single

  use_blueprint:
    path: bkbilly/certificate-expiration.yaml
    input:
      time_input: '12:00:00'
      certificate_input: sensor.cert_expiry_timestamp_techlife_nl
      days_input: 30
      notify_device: 5e3a9bc1a6710fb13b08435ab16cd62b
