---
# Send notification when there is an update for custom card / components
#
- alias: System - Notify on a custom card update
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.custom_card_tracker
      above: 0
  action:
    - service: notify.telegram_klaas
      data:
        title: '*Custom card update*'
        message: "Er zijn updates voor de custom cards"

- alias: System - Notify on a custom component update
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.custom_component_tracker
      above: 0
  action:
    - service: notify.telegram_klaas
      data:
        title: '*Custom component update*'
        message: "Er zijn updates voor de custom components/integrations"
