---
# This will show if my airco is on or off
#

- platform: template
  sensors:
    airco_status:
      friendly_name: Airco
      icon_template: mdi:air-conditioner
      device_class: power
      value_template: >-
        {{ is_state('climate.4418108384f3eb36f037','unknown') }}
