---
# This will show if my airco is on or off
#
- platform: template
  sensors:
    airco_status:
      friendly_name: Airco
      icon_template: mdi:air-conditioner
      device_class: power
      value_template: >-
        {{ states('sensor.measure_airco_power')|int >= 5 }}
