---
# Are the curtains open or closed?
#
# {{ is_state('cover.curtain_window', 'open') }}
- platform: template
  sensors:
    curtain:
      device_class: window
      value_template: >-
        {{ state_attr('cover.curtain_window', 'current_position') | int > 1 }}
