---
#
# Binary sensors that pings devices in our network.
#

# Router
- platform: ping
  host: !secret ping_switch
  name: TP-Link Router

# Google Home Living room
- platform: ping
  host: !secret google_home
  name: Google Home

# Google Cast - TV
- platform: ping
  host: !secret google_chromecast_tv
  name: Google Cast - TV

# Tablet
- platform: ping
  host: !secret ping_tablet
  name: Tablet
