---
# Determine if someone is showering
#
- platform: template
  sensors:
    shower_status:
      friendly_name: Douchen
      icon_template: mdi:shower-head
      value_template: >-
        {{ states('sensor.bathroom_humidity') | int > 75 }}
