---
- alias: '[System] - Set HA theme'
  description: >-
    Change theme based on day or night
  id: 6de4f15a-300c-46ae-ad72-a379732c8ed4
  mode: single

  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
      to: above_horizon
    - platform: state
      entity_id: sun.sun
      to: below_horizon
    - platform: state
      entity_id:
        - input_boolean.maintenance_mode
  action:
    - service_template: frontend.set_theme
      data_template:
        name: >
          {% if is_state ('input_boolean.maintenance_mode' , 'on') %} darkorange
          {% elif is_state ('sun.sun' , 'below_horizon') %} midnight_blue
          {% else %} default {% endif %}
