---
# Using the IKEA Dimmer (small round white disk) to turn on / off the kitchen lights
#
- alias: Light - Toggle lamp ON from dimmer
  initial_state: true
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_wireless_dimmer
        event: 1002
  action:
    service: light.turn_on
    entity_id: light.keuken

- alias: Light - Toggle lamp OFF from dimmer
  initial_state: true
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_wireless_dimmer
        event: 4002
  action:
    service: light.turn_off
    entity_id: light.keuken
