---
#
# Samsung alarm template sensor
#
# 5*60 means it will be 5 min back in time.
# Normally I want the sensor to switch ON 10 minutes before the alarm goes on, 
# but the Samsung alarm app keep also deviates 5 minutes from the time you have set by default.

- platform: template
  sensors:
    samsung_mobile_alarm:
      value_template: >
        {% set ts = as_timestamp(states("sensor.klaas_samsung_s9_next_alarm")) %}
        {{ ts is not none and states("sensor.time") == (ts - 5*60)|timestamp_custom ("%H:%M") }}
