---
- alias: '[Media] - Toggle TV mute'
  description: >-
    Control mute for TV
  id: 2ba53b49-f36f-40c8-9955-7cdb0188e2ae
  mode: single

  trigger:
    - platform: state
      entity_id: input_boolean.tv_mute
  action:
    service: remote.send_command
    data_template:
      entity_id: remote.harmony_hub
      device: !secret tv_id
      command: >
        {% if is_state(trigger.entity_id, 'on') %}
          Mute
        {% else %}
          Mute
        {% endif %}
