---
#
# Control mute for TV
- alias: '[Media] - Toggle TV mute'
  trigger:
    - platform: state
      entity_id: input_boolean.tv_mute
  action:
    service: remote.send_command
    data_template:
      entity_id: remote.harmony_hub
      device: !secret tv_id
      command: >
        {% if is_state(trigger.entity_id, 'on') %}
          Mute
        {% else %}
          Mute
        {% endif %}
