---
#
# Control TV power
- alias: '[Media] - Toggle TV switch on'
  trigger:
    - platform: state
      entity_id: input_boolean.tv_power
      to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.watch_tv

- alias: '[Media] - Toggle TV switch off'
  trigger:
    - platform: state
      entity_id: input_boolean.tv_power
      to: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.watch_tv

- alias: '[Media] - Turn TV boolean on'
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Tv kijken') }}"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.tv_power

- alias: '[Media] - Turn TV boolean off'
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'PowerOff') }}"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.tv_power
