---
- alias: '[House] - Operate curtains with switch'
  description: >-
    Operate the curtains with an aqara D1 1-way switch

  id: f03dd47f-b349-4462-9d16-2112b4770362

  use_blueprint:
    path: aqara_d1_1way_remote.yaml
    input:
      remote: 1207f1a3c8f5f1392bc4686c1a133b93
      cover:
        entity_id: cover.curtain_window
