---
#
# Operate the curtains with an aqara D1 1-way switch
#
- alias: '[House] - Operate curtains with switch'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        unique_id: "00:15:8d:00:04:62:00:56"
  action:
    - choose:
        # Curtain open
        - conditions:
            - condition: template
              value_template: "{{ trigger.event.data.event == 1002 }}"
          sequence:
            - service: cover.open_cover
              entity_id: cover.curtain_window

        # Curtain closing
        - conditions:
            - condition: template
              value_template: "{{ trigger.event.data.event == 1001 }}"
          sequence:
            - service: cover.close_cover
              entity_id: cover.curtain_window
