---
# Start wakeup sequence
#
- alias: '[House] - Wake up ritual'
  trigger:
    # Trigger is moment that current time is 10 minutes before alarm
    # Google Home Alarm
    - platform: state
      entity_id: binary_sensor.google_home_alarm
      to: 'on'
    # Manual Alarm
    - platform: template
      value_template: >
        {{ is_state('binary_sensor.manual_time_match_wakeup', 'on') and
           states('sensor.google_home_alarm') in ('none', 'unavailable', 'unknown') }}
  condition:
    condition: and
    conditions:
      # Condition is that I went to bed
      - condition: state
        entity_id: input_boolean.go_to_sleep
        state: 'on'
      # And I also have to be home :)
      - condition: state
        entity_id: sensor.klaas_status
        state: 'Thuis'
  action:
    # Start wake up script ritual
    - service: script.wake_up
      data_template:
        entity_id: "{{ trigger.entity_id }}"
