---
- alias: "[House] - Notify too warm in house"
  description: >-
    Notify me if it gets too warm in house

  id: b9fee44a-eca0-421a-891a-57fae1b91296
  mode: single

  trigger:
    - platform: numeric_state
      entity_id: sensor.home_temperature
      above: 30

  action:
    - service: notify.telegram_klaas
      data_template:
        title: '*Warmte alarm!*'
        message: >-
          Het is nu {{ states('sensor.home_temperature') }}°C in huis, doe een raam open!
