---
#
# A notification when there is a lightning strike in the area
- alias: '[House] - Notify if there is a thunderstorm'
  trigger:
    - platform: geo_location
      source: wwlln
      zone: zone.thunder
      event: enter
  action:
    - service: notify.telegram_klaas
      data:
        title: '*Onweer opkomst*'
        message: >
          Camera in de aanslag er is onweer in de buurt
