---
esphome:
  name: blitzwolf_lt11_bureau_rechts
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Blitzwolf LT11 Rechts"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

ota:
  password: !secret esphome_ota_password

web_server:
  port: 80
  auth:
    username: !secret esphome_web_username
    password: !secret esphome_web_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Blitzwolf LED Strip Button"
    on_press:
      - light.toggle: led_light

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Blitzwolf BW-LT11 - Rechts"
    update_interval: 60s

output:
  - platform: esp8266_pwm
    pin: GPIO14
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: GPIO12
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: GPIO4
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: GPIO5
    frequency: 1000 Hz
    id: pwm_w

light:
  - platform: rgbw
    name: "Blitzwolf BW-LT11 LED Strip - Rechts"
    color_interlock: true
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    white: pwm_w
    id: led_light

text_sensor:
  - platform: version
    hide_timestamp: true
    name: "Blitzwolf BW-LT11 Version - Rechts"
