---
# Workdesk
#

- platform: group
  name: Stellingkast
  entities:
    - light.desk_light_right_led_strip
    - light.desk_light_left_led_strip

- platform: group
  name: Bureau
  entities:
    - light.desk_light_right_led_strip
    - light.desk_light_left_led_strip
    - light.wled_workdesk
