---
name: Home Assistant CI

on:
  push:
  pull_request:
  schedule:
    - cron: 0 2 * * *

jobs:
  # YAML Lint
  yamllint:
    name: 🧹 YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v2
      - name: 🚀 Run yamllint
        uses: frenck/action-yamllint@v1

  #Remark Lint
  remarklint:
    name: Remark Lint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v2
      - name: Running Remark lint
        uses: "docker://pipelinecomponents/remark-lint:latest"
        continue-on-error: true
        with:
          args: "remark --no-stdout --color --frail --use preset-lint-recommended ."

  #Home Assistant - Stable
  home_assistant_stable:
    name: Home Assistant - Stable
    runs-on: ubuntu-latest
    needs: [yamllint, remarklint]
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v2
      - name: Copy stub file into configuration folder
        run: |
          cp ./.stubs/fake_secrets.yaml secrets.yaml
          touch ./home-assistant_v2.db
          touch ./home-assistant.log
          touch ./OZW_Log.txt
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: |
            python -m homeassistant --config . --script check_config  --info all
  
  #Home Assistant - Beta
  home_assistant_beta:
    name: Home Assistant - Beta
    runs-on: ubuntu-latest
    needs: [yamllint, remarklint]
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v2
      - name: Copy stub file into configuration folder
        run: |
          cp ./.stubs/fake_secrets.yaml secrets.yaml
          touch ./home-assistant_v2.db
          touch ./home-assistant.log
          touch ./OZW_Log.txt
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:beta"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:beta"
        with:
          args: |
            python -m homeassistant --config . --script check_config  --info all

  #Home Assistant - Dev
  home_assistant_dev:
    name: Home Assistant - Dev
    runs-on: ubuntu-latest
    needs: [yamllint, remarklint]
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v2
      - name: Copy stub file into configuration folder
        run: |
          cp ./.stubs/fake_secrets.yaml secrets.yaml
          touch ./home-assistant_v2.db
          touch ./home-assistant.log
          touch ./OZW_Log.txt
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:dev"
        with:
          args: |
            python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:dev"
        with:
          args: |
            python -m homeassistant --config . --script check_config  --info all
